name: æ„å»ºé¢„è§ˆå¹¶éƒ¨ç½²åˆ° Netlify

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: æ„å»º
    runs-on: ubuntu-22.04
    environment:
      name: é¢„è§ˆ Preview
      url: ${{ steps.netlify-deployment.outputs.NETLIFY_URL }}
    permissions:
      pull-requests: write
    steps:
      - name: æœç´¢è¯„è®º ID
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: åˆ° Netlify

      - name: åˆ›å»ºæˆ–æ›´æ–°è¯„è®º
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ğŸš§ æ­£åœ¨éƒ¨ç½²åˆ° Netlify

            | çŠ¶æ€         | URL                                  |
            |-------------|--------------------------------------|
            | ç­‰å¾…ä¸­       | `éƒ¨ç½²å®Œæˆåå°†ä¼šåœ¨æ­¤å¤„æ›´æ–° URL`           |
          edit-mode: replace

      - name: ç­¾å‡ºä»£ç 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: å®‰è£… Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: å®‰è£… pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 8

      - name: è·å– pnpm store ç›®å½•
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: é…ç½® pnpm ç¼“å­˜
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: å®‰è£…ä¾èµ–
        run: pnpm install --frozen-lockfile

      - name: å®‰è£…æ€æºé»‘ä½“
        run: |
          mkdir -p ~/.local/share/fonts
          cp public/source-han-sans.ttf ~/.local/share/fonts/source-han-sans.ttf

      - name: æ„å»º
        run: pnpm docs:build

      - name: å®‰è£… Netlify CLI
        run: pnpm install -g netlify-cli

      - name: æ¨é€åˆ° Netlify
        id: netlify
        timeout-minutes: 10
        run: |
          NETLIFY_JSON_OUTPUT=$(netlify deploy --dir .vitepress/dist --json)
          echo $NETLIFY_JSON_OUTPUT
          echo "NETLIFY_JSON_OUTPUT=$(echo $NETLIFY_JSON_OUTPUT)" >> $GITHUB_ENV
          echo "NETLIFY_URL=$(echo $NETLIFY_JSON_OUTPUT | jq -r .deploy_url)" >> $GITHUB_ENV
          cat $GITHUB_ENV
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: åˆ›å»ºæˆ–æ›´æ–°è¯„è®º
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## âœ… å·²æˆåŠŸéƒ¨ç½²åˆ° Netlify

            | çŠ¶æ€        | URL                                                 |
            |-------------|-----------------------------------------------------|
            | æˆåŠŸ         | ${{ env.NETLIFY_URL }} |
          edit-mode: replace

